name: Unit-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Install 🔧
      run: npm ci

    - name: Lint 🧹
      run: npm run lint

    # Figure out why karma has problems...
    # - name: Test 📊
    #   run: ng test --watch=false --browsers=ChromeHeadless
